### ISSUE TITLE
TestDriverException: failed to output log file. (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by imgeopineda** [ldi-github/shirates-core#108]
Hello all my test are getting a null pointer exception

Complete Error Message:

shirates.core.exception.TestDriverException: failed to output log file. (java.lang.NullPointerException)

	at shirates.core.logging.TestLog.outputLogFile(TestLog.kt:1691)
	at shirates.core.logging.TestLog.outputLogFile$default(TestLog.kt:1636)
	at shirates.core.logging.TestLog.outputLogDetail(TestLog.kt:1599)
	at shirates.core.testcode.UITestCallbackExtension.afterAll(UITestCallbackExtension.kt:337)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

Here is a copy of my build.gradle.kts file:

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.9.23"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    //maven { url = uri("https://jitpack.io") }
}

val shiratesCoreVersion = "7.4.0"
val appiumClientVersion = "9.1.0"

dependencies {
    testImplementation(kotlin("test"))

    // JUnit 5
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.1")

    // Appium
    testImplementation("io.appium:java-client:$appiumClientVersion")

    // shirates-core
    testImplementation("io.github.ldi-github:shirates-core:$shiratesCoreVersion")

    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
    testImplementation("org.apache.logging.log4j:log4j-core:2.20.0")

    // https://mvnrepository.com/artifact/org.slf4j/slf4j-nop
    testImplementation("org.slf4j:slf4j-nop:2.0.5")

    implementation("com.github.blocoio:faker:2.0.1")

    // Unit Testing
    testImplementation ("com.github.blocoio:faker:2.0.1")

    implementation("com.beust:klaxon:5.5")

    implementation("com.github.doyaaaaaken:kotlin-csv:0.6.0")

}

tasks.test {
    useJUnitPlatform()
//    jvmArgs = listOf(
//        "--add-exports", "java.desktop/sun.awt.image=ALL-UNNAMED"
//    )
//
//    // Filter test methods
//    val envIncludeTestMatching = System.getenv("includeTestsMatching") ?: "*"
//    val list = envIncludeTestMatching.split(",").map { it.trim() }
//    filter {
//        for (item in list) {
//            println("includeTestMatching($item)")
//            includeTestsMatching(item)
//        }
//    }
}

kotlin {
    jvmToolchain(17)
}

**Comment by imgeopineda** [comment]
I was able to fix it. Deleting Test Results, made it work again somehow.

**Comment by ldi-github** [comment]
Thank you for your feedback.
I think your way of handling this is the right way.
The format of `TestLog(commandList).log` was changed on version 7.4.0.
