### ISSUE TITLE
Unable to start session after updating to macOS 15.2

### ISSUE THREAD

**Issue by ldi-github** [ldi-github/shirates-core#119]
## Problem

`shirates.core.exception.TestDriverException: Could not find connected device. (platformVersion=14)

	at shirates.core.utility.android.AndroidDeviceUtility.getConnectedDeviceInfo(AndroidDeviceUtility.kt:291)
	at shirates.core.utility.android.AndroidDeviceUtility.getOrCreateAndroidDeviceInfo(AndroidDeviceUtility.kt:136)
	at shirates.core.configuration.TestProfile.completeProfileWithDeviceInformation(TestProfile.kt:605)
	at shirates.core.testcode.UITestBase.setupCore(UITestBase.kt:371)
	at shirates.core.testcode.UITestBase.setupFromTestrun(UITestBase.kt:231)
	at shirates.core.testcode.UITestBase.setupFromTestrun$default(UITestBase.kt:213)
	at shirates.core.testcode.UITestBase.setup(UITestBase.kt:200)
	at shirates.core.testcode.UITestCallbackExtension.beforeEach(UITestCallbackExtension.kt:185)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
`

**Comment by ldi-github** [comment]
Fails in shell execution.

`ShellUtility.executeCommand("adb", "devices", "-l")`

returns empty result.

Something wrong in DefaultExecutor of Apache commons-exec.

**Comment by ldi-github** [comment]
Fixed on 7.5.6 https://github.com/ldi-github/shirates-core/commit/3df0ce794dfb29b65e8603be463dc109524e6460
